### ISSUE TITLE
Targets not appearing

### ISSUE THREAD

**Issue by willoughby** [GiGurra/leavu3#5]
We tested with 3 ships. But targets picked up on our radar wasn't shared with the group only locked targets. Is this the desired functionality ?

**Comment by GiGurra** [comment]
Yes. Only locked targets are shared - that is the current intended behavior right now.

Linked locked targets are drawn on HSD (both with and without burnthrough),
while on FCR only burnthrough targets are drawn.

**Comment by willoughby** [comment]
Thats great thanks.
